model_list:
  - model_name: gemma-4-31b-it
    litellm_params:
      custom_llm_provider: gemini
      reasoning_effort: "medium"
      rpm: 40
      timeout: "120"
      stream_timeout: "120"
      litellm_credential_name: "Google AI Studio"
      use_in_pass_through: false
      use_litellm_proxy: false
      use_xai_oauth: false
      merge_reasoning_content_in_choices: false
      tags: []
      model: gemini/gemma-4-31b-it
      guardrails: []
      metadata: {}
    model_info:
      db_model: true
      blocked: false
      mode: chat
      access_groups: []
      direct_access: true
      access_via_team_ids: []
      max_tokens: 256000
      max_input_tokens: 256000
      supports_reasoning: true
