services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: standalone
    labels:
      traefik.enable: true
      traefik.http.routers.librespeed.rule: Host(`librespeed.${DOMAIN}`)
      traefik.http.routers.librespeed.entrypoints: websecure
      traefik.http.routers.librespeed.tls: true
      traefik.http.services.librespeed.loadbalancer.server.port: 8080
      traefik.docker.network: proxy-net
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
