services:
  adguardhome:
    ports:
      - "3000:3000"
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 853:853/udp
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /media/storage/adguard/db:/opt/adguardhome/work
      - /media/storage/adguard/data/conf:/opt/adguardhome/conf
      - /media/storage/adguard/data/certs:/opt/certs:ro
