services:
  adguardhome:
    ports:
      - "3000:3000"
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 853:853/udp
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/adguard/db:/opt/adguardhome/work
      - ${DATA_PATH}/adguard/conf:/opt/adguardhome/conf
      - ${DATA_PATH}/adguard/certs:/opt/certs:ro
