services:
  copyparty:
    image: copyparty/im:latest
    restart: always
    user: "1000:1000"
    volumes:
      - ./cpp:/cfg:z
      - /media/storage/encrypted:/w:z

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so
      PYTHONUNBUFFERED: 1

    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
    labels:
      traefik.enable: true
      traefik.http.routers.copyparty.rule: Host(`encfs.${DOMAIN}`)
      traefik.http.routers.copyparty.entrypoints: websecure
      traefik.http.routers.copyparty.tls: true
      traefik.http.services.copyparty.loadbalancer.server.port: 3923
      traefik.http.middlewares.copyparty-real-ip.headers.customrequestheaders.X-Forwarded-Proto: https
      traefik.http.routers.copyparty.middlewares: copyparty-real-ip
      traefik.docker.network: proxy-net
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
