services:
  beszel-agent:
    image: henrygd/beszel-agent:alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - /media/storage/data/beszel/agent_data:/var/lib/beszel-agent
      - /media/storage/data/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/adri/.cache/beszel:/extra-filesystems/sda:ro
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
    environment:
      LISTEN: 45876
      HUB_URL: ${HUB_URL}
      TOKEN: ${TOKEN}
      KEY: ${KEY}
