http:
  routers:
    adguard:
      rule: "Host(`adguard.{{ env "DOMAIN" }}`)"
      entryPoints:
        - websecure
      tls: true
      service: adguard

  services:
    adguard:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.0.1:3000"

