http:
  routers:
    tailscale-srv-backrest:
      rule: "Host(`backrest.srv.oliviero.xyz`)"
      entryPoints:
        - websecure
      tls:
        certresolver: production
      service: tailscale-srv-backrest-service

  services:
    tailscale-srv-backrest-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://100.111.1.2:9898"

