http:
  routers:
    emqx:
      rule: "Host(`emqx.{{ env "DOMAIN" }}`)"
      entryPoints:
        - websecure
      tls: true
      service: emqx

  services:
    emqx:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.0.1:18083"

