http:
  routers:
    haos:
      rule: "Host(`haos.{{ env "DOMAIN" }}`)"
      entryPoints:
        - websecure
      tls: true
      service: haos

  services:
    haos:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://172.17.0.1:8123"
