http:
  routers:
    haos:
      rule: "Host(`haos.oliviero.xyz`)"
      entryPoints:
        - websecure
      tls:
        certresolver: production
      service: haos

  services:
    haos:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://172.17.0.1:8123"
