http:
  routers:
    lemonade:
      rule: "Host(`lemonade.oliviero.xyz`)"
      entryPoints:
        - websecure
      tls: true
      service: lemonade

  services:
    lemonade:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.120:8000"
