http:
  routers:
    llamacpp:
      rule: "Host(`llamacpp.{{ env "DOMAIN" }}`)"
      entryPoints:
        - websecure
      tls: true
      service: llamacpp

  services:
    llamacpp:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.120:8080"
