secrets:
  rpc_secret:
    file: ./secrets/rpc_secret

services:
  garage:
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    secrets:
      - rpc_secret
    environment:
      - GARAGE_RPC_SECRET_FILE=/run/secrets/rpc_secret
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ${DATA_PATH}/garage/meta:/var/lib/garage/meta
      - ${DATA_PATH}/garage/data:/var/lib/garage/data
    labels:
      traefik.enable: true
      traefik.http.routers.garage.service: garage
      traefik.http.routers.garage.rule: Host(`s3.${DOMAIN}`)
      traefik.http.routers.garage.entrypoints: websecure
      traefik.http.routers.garage.tls: true
      traefik.http.services.garage.loadbalancer.server.port: 3900

      traefik.http.routers.garage-web.service: garage-web
      traefik.http.routers.garage-web.rule: Host(`garage.${DOMAIN}`)
      traefik.http.routers.garage-web.entrypoints: websecure
      traefik.http.routers.garage-web.tls: true
      traefik.http.services.garage-web.loadbalancer.server.port: 3902
      traefik.http.routers.garage-web.middlewares: compression
      traefik.http.middlewares.compression.compress: true
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
