secrets:
  cf_email:
    file: ./secrets/cf_email_secret
  cf_key:
    file: ./secrets/cf_key_secret
  cf_dns_token:
    file: ./secrets/cf_dns_token_secret
  cf_zone_token:
    file: ./secrets/cf_zone_token_secret
  basic_auth_users:
    file: ./secrets/basicauth_users_secret

include:
  - ./dumper-compose.yml

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    secrets:
      - cf_email
      - cf_key
      - cf_dns_token
      - cf_zone_token
      - basic_auth_users
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--log.level=INFO"
      # - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.dns.address=:53/udp"
      - "--entryPoints.dnstcp.address=:53/tcp"
      - "--entryPoints.dot.address=:853"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.http.tls.certresolver=production"
      - "--entrypoints.websecure.http.tls.domains[0].main=oliviero.xyz"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.oliviero.xyz"
      - "--entrypoints.git.address=:222"
      # - "--entrypoints.dnstcp.address=:53"
      # - "--entrypoints.dnsudp.address=:53"
      - "--certificatesresolvers.production.acme.dnschallenge=true"
      - "--certificatesresolvers.production.acme.dnschallenge.provider=cloudflare"
      #- "--certificatesresolvers.production.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.production.acme.email=adrianoliviero23@gmail.com"
      - "--certificatesresolvers.production.acme.storage=/letsencrypt/acme.json"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 222
        published: 222
        protocol: tcp
        mode: host
    environment:
      # - CF_API_EMAIL=${CF_API_EMAIL}
      # - CF_API_KEY=${CF_API_KEY}
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_token
      - CF_ZONE_API_TOKEN_FILE=/run/secrets/cf_zone_token
      # - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      # - CF_ZONE_API_TOKEN=${CF_ZONE_API_TOKEN}
    volumes:
      - /media/storage/data/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`tf.oliviero.xyz`)
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.tls.certresolver: production
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: auth
      traefik.http.middlewares.auth.basicauth.usersFile: /run/secrets/basic_auth_users
    networks:
      - proxy-net

networks:
  proxy-net:
    name: proxy-net
    attachable: true
