include:
  - webui.yml

services:
  ollama:
    image: ollama/ollama:rocm
    restart: unless-stopped
    privileged: true
    volumes:
      - ./ollama:/root/.ollama
    devices:
      - /dev/dri
      - /dev/kfd
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128
      - OLLAMA_CONTEXT_LENGTH=16384
      - HSA_ENABLE_SDMA=0
      - HSA_DISABLE_FRAGMENT_ALLOCATOR=1
      - OLLAMA_KV_CACHE_TYPE=q8_0
      - OLLAMA_KEEP_ALIVE=0
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    ports:
      - 11434:11434
    pull_policy: always
    tty: true
