services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    volumes:
      - ./webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - AIOHTTP_CLIENT_TIMEOUT=6000
      - WEBUI_TIMEOUT=6000
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

